"""Command dictionary and helpers for the serial controller protocol.

Generated from docs/stm_command_reference_from_code.xlsx.

This module keeps the raw command names, metadata, sensor field ordering,
and error code mapping in one place so the FastAPI backend can import them
from a separate file.
"""
from __future__ import annotations

import re
from typing import Any

COMMANDS = {'LASER_SET_ARM_EN': {'name': 'LASER_SET_ARM_EN',
                      'cmd': 'LASER_SET_ARM_EN',
                      'section': 'LASER CONTROL',
                      'parameters': 'int/bool; >0 = arm, <=0 = disarm',
                      'returns': '[LASER_SET_ARM_EN][arg]->[OK][TS]',
                      'description': 'Arms or disarms laser. If disarming while a process is active, stops calibration, target sequence, '
                                     'and laser first. Cannot arm while Peltier cooling is disabled.',
                      'example': 'LASER_SET_ARM_EN 1',
                      'returns_nok': '[LASER_SET_ARM_EN][arg]->[NOK][reason][TS]',
                      'example_return': '[LASER_SET_ARM_EN][1]->[OK][12523]'},
 'LASER_GET_ARM_EN': {'name': 'LASER_GET_ARM_EN',
                      'cmd': 'LASER_GET_ARM_EN',
                      'section': 'LASER CONTROL',
                      'parameters': '~',
                      'returns': '[LASER_GET_ARM_EN]->[1|0][TS]',
                      'description': 'Returns whether laser is armed.',
                      'example': 'LASER_GET_ARM_EN',
                      'example_return': '[LASER_GET_ARM_EN]->[1][12523]'},
 'LASER_SET_RED_DOT_EN': {'name': 'LASER_SET_RED_DOT_EN',
                          'cmd': 'LASER_SET_RED_DOT_EN',
                          'section': 'LASER CONTROL',
                          'parameters': 'int/bool; >0 = on, <=0 = off',
                          'returns': '[LASER_SET_RED_DOT_EN][arg]->[OK][TS]',
                          'description': 'Turns red-dot mode on/off. If APP checkVacuum is enabled, enabling is blocked when vacuum is not '
                                         'acceptable.',
                          'example': 'LASER_SET_RED_DOT_EN 1',
                          'returns_nok': '[LASER_SET_RED_DOT_EN][arg]->[NOK][reason][TS]',
                          'example_return': '[LASER_SET_RED_DOT_EN][1]->[OK][12523]'},
 'LASER_GET_RED_DOT_EN': {'name': 'LASER_GET_RED_DOT_EN',
                          'cmd': 'LASER_GET_RED_DOT_EN',
                          'section': 'LASER CONTROL',
                          'parameters': '~',
                          'returns': '[LASER_GET_RED_DOT_EN]->[1|0][TS]',
                          'description': 'Returns whether red-dot mode is active.',
                          'example': 'LASER_GET_RED_DOT_EN',
                          'example_return': '[LASER_GET_RED_DOT_EN]->[0][12523]'},
 'LASER_SET_CHANNEL_PWR': {'name': 'LASER_SET_CHANNEL_PWR',
                           'cmd': 'LASER_SET_CHANNEL_PWR',
                           'section': 'LASER CONTROL',
                           'parameters': '808PWR,980PWR,1064PWR (CSV integers)',
                           'returns': '[LASER_SET_CHANNEL_PWR][p1,p2,p3]->[OK][TS]',
                           'description': 'Sets 808/980/1064 power percentages and marks channels active when power > 0.',
                           'example': 'LASER_SET_CHANNEL_PWR 20,25,50',
                           'returns_nok': '[LASER_SET_CHANNEL_PWR][p1,p2,p3]->[NOK][reason][TS]',
                           'example_return': '[LASER_SET_CHANNEL_PWR][20,25,50]->[OK][12523]',
                           'notes': 'Channel power values are passed through as 0-100 integers; 0 disables that channel.'},
 'LASER_GET_CHANNEL_PWR': {'name': 'LASER_GET_CHANNEL_PWR',
                           'cmd': 'LASER_GET_CHANNEL_PWR',
                           'section': 'LASER CONTROL',
                           'parameters': '~',
                           'returns': '[LASER_GET_CHANNEL_PWR]->[808PWR,980PWR,1064PWR][TS]',
                           'description': 'Returns configured channel powers.',
                           'example': 'LASER_GET_CHANNEL_PWR',
                           'example_return': '[LASER_GET_CHANNEL_PWR]->[20,25,50][12523]'},
 'LASER_FIRE': {'name': 'LASER_FIRE',
                'cmd': 'LASER_FIRE',
                'section': 'LASER CONTROL',
                'parameters': 'duration_ms',
                'returns': '[LASER_FIRE][duration]->[OK][TS]',
                'description': 'Fires laser for given pulse length. Blocked unless app is RUNNING, no other process is active, and vacuum '
                               'is acceptable when vacuum checking is enabled.',
                'example': 'LASER_FIRE 20',
                'returns_nok': '[LASER_FIRE][duration]->[NOK][reason][TS]',
                'example_return': '[LASER_FIRE][20]->[OK][12523]'},
 'LASER_STOP': {'name': 'LASER_STOP',
                'cmd': 'LASER_STOP',
                'section': 'LASER CONTROL',
                'parameters': '~',
                'returns': '[LASER_STOP]->[OK][TS]',
                'description': 'Stops laser immediately.',
                'example': 'LASER_STOP',
                'example_return': '[LASER_STOP]->[OK][12523]'},
 'LASER_IS_ACTIVE': {'name': 'LASER_IS_ACTIVE',
                     'cmd': 'LASER_IS_ACTIVE',
                     'section': 'LASER CONTROL',
                     'parameters': '~',
                     'returns': '[LASER_IS_ACTIVE]->[1|0][TS]',
                     'description': 'Returns whether laser pulse is active.',
                     'example': 'LASER_IS_ACTIVE',
                     'example_return': '[LASER_IS_ACTIVE]->[0][12523]'},
 'LASER_GET_STATE': {'name': 'LASER_GET_STATE',
                     'cmd': 'LASER_GET_STATE',
                     'section': 'LASER CONTROL',
                     'parameters': '~',
                     'returns': '[LASER_GET_STATE]->[STATE_STRING][TS]',
                     'description': 'Returns laser controller state string.',
                     'example': 'LASER_GET_STATE',
                     'example_return': '[LASER_GET_STATE]->[LASER_STATE_ARMED_IDLE][12523]',
                     'notes': 'Exact state names come from Laser_GetStateAsString().'},
 'LASER_GET_LAST_ERROR': {'name': 'LASER_GET_LAST_ERROR',
                          'cmd': 'LASER_GET_LAST_ERROR',
                          'section': 'LASER CONTROL',
                          'parameters': '~',
                          'returns': '[LASER_GET_LAST_ERROR]->[Error string][ERROR_CODE][TS]',
                          'description': 'Returns laser last error string and code.',
                          'example': 'LASER_GET_LAST_ERROR',
                          'example_return': '[LASER_GET_LAST_ERROR]->[No error][LASER_ERROR_NONE][12523]'},
 'LASER_CLEAR_ERROR': {'name': 'LASER_CLEAR_ERROR',
                       'cmd': 'LASER_CLEAR_ERROR',
                       'section': 'LASER CONTROL',
                       'parameters': '~',
                       'returns': '[LASER_CLEAR_ERROR]->[OK][TS]',
                       'description': 'Clears laser error.',
                       'example': 'LASER_CLEAR_ERROR',
                       'example_return': '[LASER_CLEAR_ERROR]->[OK][12523]'},
 'PELTIER_SET_COOLING_EN': {'name': 'PELTIER_SET_COOLING_EN',
                            'cmd': 'PELTIER_SET_COOLING_EN',
                            'section': 'PELTIER CONTROL',
                            'parameters': 'int/bool; >0 = enable, <=0 = disable',
                            'returns': '[PELTIER_SET_COOLING_EN][arg]->[OK][TS]',
                            'description': 'Enables/disables Peltier cooling. Cannot modify while a process is active or app not RUNNING. '
                                           'Cannot disable while laser is armed.',
                            'example': 'PELTIER_SET_COOLING_EN 1',
                            'returns_nok': '[PELTIER_SET_COOLING_EN][arg]->[NOK][reason][TS]',
                            'example_return': '[PELTIER_SET_COOLING_EN][1]->[OK][12523]'},
 'PELTIER_GET_COOLING_EN': {'name': 'PELTIER_GET_COOLING_EN',
                            'cmd': 'PELTIER_GET_COOLING_EN',
                            'section': 'PELTIER CONTROL',
                            'parameters': '~',
                            'returns': '[PELTIER_GET_COOLING_EN]->[1|0][TS]',
                            'description': 'Returns whether Peltier is enabled.',
                            'example': 'PELTIER_GET_COOLING_EN',
                            'example_return': '[PELTIER_GET_COOLING_EN]->[1][12523]'},
 'PELTIER_GET_STATE': {'name': 'PELTIER_GET_STATE',
                       'cmd': 'PELTIER_GET_STATE',
                       'section': 'PELTIER CONTROL',
                       'parameters': '~',
                       'returns': '[PELTIER_GET_STATE]->[STATE_STRING][TS]',
                       'description': 'Returns Peltier state string.',
                       'example': 'PELTIER_GET_STATE',
                       'example_return': '[PELTIER_GET_STATE]->[PELTIER_STATE_ENABLED][12523]'},
 'PELTIER_GET_LAST_ERROR': {'name': 'PELTIER_GET_LAST_ERROR',
                            'cmd': 'PELTIER_GET_LAST_ERROR',
                            'section': 'PELTIER CONTROL',
                            'parameters': '~',
                            'returns': '[PELTIER_GET_LAST_ERROR]->[Error string][ERROR_CODE][TS]',
                            'description': 'Returns Peltier last error string and code.',
                            'example': 'PELTIER_GET_LAST_ERROR',
                            'example_return': '[PELTIER_GET_LAST_ERROR]->[No error][PELTIER_ERROR_NONE][12523]'},
 'PELTIER_CLEAR_ERROR': {'name': 'PELTIER_CLEAR_ERROR',
                         'cmd': 'PELTIER_CLEAR_ERROR',
                         'section': 'PELTIER CONTROL',
                         'parameters': '~',
                         'returns': '[PELTIER_CLEAR_ERROR]->[OK][TS]',
                         'description': 'Clears Peltier error.',
                         'example': 'PELTIER_CLEAR_ERROR',
                         'example_return': '[PELTIER_CLEAR_ERROR]->[OK][12523]'},
 'TARGET_SET_POS': {'name': 'TARGET_SET_POS',
                    'cmd': 'TARGET_SET_POS',
                    'section': 'TARGET CONTROL',
                    'parameters': 'X,Y (CSV, each 0-4095)',
                    'returns': '[TARGET_SET_POS][X,Y]->[OK][TS]',
                    'description': 'Sets galvo target position. Blocked while a process is active or app not RUNNING.',
                    'example': 'TARGET_SET_POS 1500,2000',
                    'returns_nok': '[TARGET_SET_POS][X,Y]->[NOK][reason][TS]',
                    'example_return': '[TARGET_SET_POS][1500,2000]->[OK][12523]'},
 'TARGET_GET_POS': {'name': 'TARGET_GET_POS',
                    'cmd': 'TARGET_GET_POS',
                    'section': 'TARGET CONTROL',
                    'parameters': '~',
                    'returns': '[TARGET_GET_POS]->[X,Y][TS]',
                    'description': 'Returns commanded target position.',
                    'example': 'TARGET_GET_POS',
                    'returns_nok': '[TARGET_GET_POS]->[NOK][reason][TS]',
                    'example_return': '[TARGET_GET_POS]->[1500,2000][12523]'},
 'TARGET_GET_FB_POS': {'name': 'TARGET_GET_FB_POS',
                       'cmd': 'TARGET_GET_FB_POS',
                       'section': 'TARGET CONTROL',
                       'parameters': '~',
                       'returns': '[TARGET_GET_FB_POS]->[Gx,Gy][TS]',
                       'description': 'Returns raw galvo feedback values from ADC acquisition.',
                       'example': 'TARGET_GET_FB_POS',
                       'returns_nok': '[TARGET_GET_FB_POS]->[NOK][Feedback position is not valid][TS]',
                       'example_return': '[TARGET_GET_FB_POS]->[2033,1989][12523]'},
 'TARGET_SET_NEW_TARGET': {'name': 'TARGET_SET_NEW_TARGET',
                           'cmd': 'TARGET_SET_NEW_TARGET',
                           'section': 'TARGET CONTROL',
                           'parameters': 'X0,Y0,X1,Y1,808PWR,980PWR,1064PWR,duration_ms',
                           'returns': '[TARGET_SET_NEW_TARGET][args]->[OK][TS]',
                           'description': 'Adds a target line/point. Power here is allowed 0-100. Pulse length must be '
                                          'TARGET_CTRL_MIN_PULSE_MS..maxFireDuration.',
                           'example': 'TARGET_SET_NEW_TARGET 1500,1000,2000,1500,20,10,15,50',
                           'returns_nok': '[TARGET_SET_NEW_TARGET][args]->[NOK][reason][TS]',
                           'example_return': '[TARGET_SET_NEW_TARGET][1500,1000,2000,1500,20,10,15,50]->[OK][12523]'},
 'TARGET_CLEAR_TARGETS': {'name': 'TARGET_CLEAR_TARGETS',
                          'cmd': 'TARGET_CLEAR_TARGETS',
                          'section': 'TARGET CONTROL',
                          'parameters': '~',
                          'returns': '[TARGET_CLEAR_TARGETS]->[OK][TS]',
                          'description': 'Clears target list.',
                          'example': 'TARGET_CLEAR_TARGETS',
                          'returns_nok': '[TARGET_CLEAR_TARGETS]->[NOK][reason][TS]',
                          'example_return': '[TARGET_CLEAR_TARGETS]->[OK][12523]'},
 'TARGET_GET_TARGET': {'name': 'TARGET_GET_TARGET',
                       'cmd': 'TARGET_GET_TARGET',
                       'section': 'TARGET CONTROL',
                       'parameters': 'index',
                       'returns': '[TARGET_GET_TARGET]->[idx,x0,y0,x1,y1,p808,p980,p1064,duration][TS]',
                       'description': 'Returns target line at index.',
                       'example': 'TARGET_GET_TARGET 5',
                       'returns_nok': '[TARGET_GET_TARGET][idx]->[NOK][reason][TS]',
                       'example_return': '[TARGET_GET_TARGET]->[5,1500,1000,2000,1500,20,10,15,50][12523]'},
 'TARGET_GET_ALL_TARGETS': {'name': 'TARGET_GET_ALL_TARGETS',
                            'cmd': 'TARGET_GET_ALL_TARGETS',
                            'section': 'TARGET CONTROL',
                            'parameters': '~',
                            'returns': 'Header: [TARGET_GET_ALL_TARGETS]->[Count,N][TS]; then N data lines '
                                       '[TARGET_GET_ALL_TARGETS]->[idx,x0,y0,x1,y1,p808,p980,p1064,duration]; then '
                                       '[TARGET_GET_ALL_TARGETS]->[END][TS]',
                            'description': 'Returns all valid target lines. Blocked while process is active.',
                            'example': 'TARGET_GET_ALL_TARGETS',
                            'returns_nok': '[TARGET_GET_ALL_TARGETS]->[NOK][reason][TS]',
                            'example_return': '[TARGET_GET_ALL_TARGETS]->[Count,3][12523]'},
 'TARGET_SET_MODE': {'name': 'TARGET_SET_MODE',
                     'cmd': 'TARGET_SET_MODE',
                     'section': 'TARGET CONTROL',
                     'parameters': 'numeric enum (TargetMode_t)',
                     'returns': '[TARGET_SET_MODE][arg]->[OK][TS]',
                     'description': 'Sets target mode. Implementation parses an integer and casts to TargetMode_t.',
                     'example': 'TARGET_SET_MODE 0',
                     'returns_nok': '[TARGET_SET_MODE][arg]->[NOK][reason][TS]',
                     'example_return': '[TARGET_SET_MODE][0]->[OK][12523]',
                     'notes': 'Important: code does NOT parse strings like SINGLE/AUTO. It expects numeric enum values.'},
 'TARGET_GET_MODE': {'name': 'TARGET_GET_MODE',
                     'cmd': 'TARGET_GET_MODE',
                     'section': 'TARGET CONTROL',
                     'parameters': '~',
                     'returns': '[TARGET_GET_MODE]->[MODE_STRING][TS]',
                     'description': 'Returns target mode string.',
                     'example': 'TARGET_GET_MODE',
                     'example_return': '[TARGET_GET_MODE]->[TARGET_MODE_SINGLE][12523]'},
 'TARGET_START': {'name': 'TARGET_START',
                  'cmd': 'TARGET_START',
                  'section': 'TARGET CONTROL',
                  'parameters': '~',
                  'returns': '[TARGET_START]->[OK][TS]',
                  'description': 'Starts target process. Requires RUNNING state, no active process, and acceptable vacuum when checkVacuum '
                                 'is enabled.',
                  'example': 'TARGET_START',
                  'returns_nok': '[TARGET_START]->[NOK][reason][TS]',
                  'example_return': '[TARGET_START]->[OK][12523]'},
 'TARGET_HALT': {'name': 'TARGET_HALT',
                 'cmd': 'TARGET_HALT',
                 'section': 'TARGET CONTROL',
                 'parameters': '~',
                 'returns': '[TARGET_HALT]->[OK][TS]',
                 'description': 'Halts active target process. Requires app RUNNING.',
                 'example': 'TARGET_HALT',
                 'returns_nok': '[TARGET_HALT]->[NOK][reason][TS]',
                 'example_return': '[TARGET_HALT]->[OK][12523]'},
 'TARGET_STOP': {'name': 'TARGET_STOP',
                 'cmd': 'TARGET_STOP',
                 'section': 'TARGET CONTROL',
                 'parameters': '~',
                 'returns': '[TARGET_STOP]->[OK][TS]',
                 'description': 'Stops target process. Requires app RUNNING.',
                 'example': 'TARGET_STOP',
                 'returns_nok': '[TARGET_STOP]->[NOK][reason][TS]',
                 'example_return': '[TARGET_STOP]->[OK][12523]'},
 'TARGET_CONTINUE': {'name': 'TARGET_CONTINUE',
                     'cmd': 'TARGET_CONTINUE',
                     'section': 'TARGET CONTROL',
                     'parameters': '~',
                     'returns': '[TARGET_CONTINUE]->[OK][TS]',
                     'description': 'Continues halted target process. Requires app RUNNING.',
                     'example': 'TARGET_CONTINUE',
                     'returns_nok': '[TARGET_CONTINUE]->[NOK][reason][TS]',
                     'example_return': '[TARGET_CONTINUE]->[OK][12523]'},
 'TARGET_GET_STATE': {'name': 'TARGET_GET_STATE',
                      'cmd': 'TARGET_GET_STATE',
                      'section': 'TARGET CONTROL',
                      'parameters': '~',
                      'returns': '[TARGET_GET_STATE]->[STATE_STRING][TS]',
                      'description': 'Returns target controller state string.',
                      'example': 'TARGET_GET_STATE',
                      'example_return': '[TARGET_GET_STATE]->[TARGET_STATE_IDLE][12523]'},
 'TARGET_GET_LAST_ERROR': {'name': 'TARGET_GET_LAST_ERROR',
                           'cmd': 'TARGET_GET_LAST_ERROR',
                           'section': 'TARGET CONTROL',
                           'parameters': '~',
                           'returns': '[TARGET_GET_LAST_ERROR]->[Error string][ERROR_CODE][TS]',
                           'description': 'Returns target controller last error string and code.',
                           'example': 'TARGET_GET_LAST_ERROR',
                           'example_return': '[TARGET_GET_LAST_ERROR]->[No error][TARGET_ERROR_NONE][12523]'},
 'TARGET_CLEAR_ERROR': {'name': 'TARGET_CLEAR_ERROR',
                        'cmd': 'TARGET_CLEAR_ERROR',
                        'section': 'TARGET CONTROL',
                        'parameters': '~',
                        'returns': '[TARGET_CLEAR_ERROR]->[OK][TS]',
                        'description': 'Clears target controller error. Requires app RUNNING.',
                        'example': 'TARGET_CLEAR_ERROR',
                        'returns_nok': '[TARGET_CLEAR_ERROR]->[NOK][reason][TS]',
                        'example_return': '[TARGET_CLEAR_ERROR]->[OK][12523]'},
 'SENSORS_GET_VALUES': {'name': 'SENSORS_GET_VALUES',
                        'cmd': 'SENSORS_GET_VALUES',
                        'section': 'SENSOR CONTROL',
                        'parameters': '~',
                        'returns': "Two plain text lines are sent, not bracketed command format: line 1 starts 'ADC: ...'; line 2 starts "
                                   "'I2C: ...'",
                        'description': 'Returns latest ADC and I2C converted values. Requires app RUNNING and all sensor-valid flags set.',
                        'example': 'SENSORS_GET_VALUES',
                        'returns_nok': '[SENSORS_GET_VALUES]->[NOK][reason][TS]',
                        'example_return': 'ADC: ADCts:..., Iin:... / I2C: Pts:..., P:...'},
 'SENSORS_GET_STATE': {'name': 'SENSORS_GET_STATE',
                       'cmd': 'SENSORS_GET_STATE',
                       'section': 'SENSOR CONTROL',
                       'parameters': '~',
                       'returns': '[SENSORS_GET_STATE]->[ADC_STATE][I2C_STATE][TS]',
                       'description': 'Returns ADC and I2C acquisition state strings.',
                       'example': 'SENSORS_GET_STATE',
                       'example_return': '[SENSORS_GET_STATE]->[ADC_ACQ_STATE_DONE][I2C_ACQ_STATE_IDLE][12523]'},
 'SENSORS_GET_LAST_ERROR': {'name': 'SENSORS_GET_LAST_ERROR',
                            'cmd': 'SENSORS_GET_LAST_ERROR',
                            'section': 'SENSOR CONTROL',
                            'parameters': '~',
                            'returns': '[SENSORS_GET_LAST_ERROR]->[ADC error string][ADC error code][I2C error string][I2C error code][TS]',
                            'description': 'Returns last ADC and I2C acquisition errors.',
                            'example': 'SENSORS_GET_LAST_ERROR',
                            'example_return': '[SENSORS_GET_LAST_ERROR]->[No error][ADC_ACQ_ERROR_NONE][No '
                                              'error][I2C_ACQ_ERROR_NONE][12523]'},
 'SENSORS_CLEAR_ERROR': {'name': 'SENSORS_CLEAR_ERROR',
                         'cmd': 'SENSORS_CLEAR_ERROR',
                         'section': 'SENSOR CONTROL',
                         'parameters': '~',
                         'returns': '[SENSORS_CLEAR_ERROR]->[OK][TS]',
                         'description': 'Clears ADC and I2C acquisition errors.',
                         'example': 'SENSORS_CLEAR_ERROR',
                         'example_return': '[SENSORS_CLEAR_ERROR]->[OK][12523]'},
 'APP_PING': {'name': 'APP_PING',
              'cmd': 'APP_PING',
              'section': 'APP CONTROL',
              'parameters': '~',
              'returns': '[APP_PING]->[OK][TS]',
              'description': 'Heartbeat / presence check.',
              'example': 'APP_PING',
              'example_return': '[APP_PING]->[OK][12523]'},
 'APP_GET_COMMANDS': {'name': 'APP_GET_COMMANDS',
                      'cmd': 'APP_GET_COMMANDS',
                      'section': 'APP CONTROL',
                      'parameters': '~',
                      'returns': 'Header: [APP_GET_COMMANDS]->[Count,N][TS]; then N lines [APP_GET_COMMANDS]->[CMD]; then '
                                 '[APP_GET_COMMANDS]->[END][TS]',
                      'description': 'Returns command list from g_cmdTable.',
                      'example': 'APP_GET_COMMANDS',
                      'example_return': '[APP_GET_COMMANDS]->[Count,70][12523]'},
 'APP_GET_LIMITS': {'name': 'APP_GET_LIMITS',
                    'cmd': 'APP_GET_LIMITS',
                    'section': 'APP CONTROL',
                    'parameters': '~',
                    'returns': 'Header: [APP_GET_LIMITS]->[Count,18][TS]; then 18 text lines with current limits; then '
                               '[APP_GET_LIMITS]->[END][TS]',
                    'description': 'Returns current runtime limits and intervals. Some values are dynamic and depend on current parameter '
                                   'set.',
                    'example': 'APP_GET_LIMITS',
                    'returns_nok': '[APP_GET_LIMITS]->[NOK][Cannot get limits while process is running][TS]',
                    'example_return': '[APP_GET_LIMITS]->[Count,18][12523]'},
 'APP_RESET': {'name': 'APP_RESET',
               'cmd': 'APP_RESET',
               'section': 'APP CONTROL',
               'parameters': '~',
               'returns': '[APP_RESET]->[OK][TS]',
               'description': 'Replies OK, waits 10 ms, then triggers MCU reset.',
               'example': 'APP_RESET',
               'example_return': '[APP_RESET]->[OK][12523]'},
 'APP_GET_PROC_TIME': {'name': 'APP_GET_PROC_TIME',
                       'cmd': 'APP_GET_PROC_TIME',
                       'section': 'APP CONTROL',
                       'parameters': '~',
                       'returns': '[APP_GET_PROC_TIME]->[OK][TS]',
                       'description': 'Implemented response currently only returns OK + timestamp via Comm_ReplyOk().',
                       'example': 'APP_GET_PROC_TIME',
                       'example_return': '[APP_GET_PROC_TIME]->[OK][12523]',
                       'notes': 'Code/comment mismatch: handler does not return process uptime value.'},
 'APP_SET_VACUUM_EN': {'name': 'APP_SET_VACUUM_EN',
                       'cmd': 'APP_SET_VACUUM_EN',
                       'section': 'APP CONTROL',
                       'parameters': 'int/bool; >0 = on, <=0 = off',
                       'returns': '[APP_SET_VACUUM_EN][arg]->[OK][TS]',
                       'description': 'Controls vacuum switch output. Blocked while process active or app not RUNNING.',
                       'example': 'APP_SET_VACUUM_EN 1',
                       'returns_nok': '[APP_SET_VACUUM_EN]->[NOK][reason][TS] or [APP_SET_VACUUM_EN][arg]->[NOK][reason][TS]',
                       'example_return': '[APP_SET_VACUUM_EN][1]->[OK][12523]'},
 'APP_GET_VACUUM_EN': {'name': 'APP_GET_VACUUM_EN',
                       'cmd': 'APP_GET_VACUUM_EN',
                       'section': 'APP CONTROL',
                       'parameters': '~',
                       'returns': '[APP_GET_VACUUM_EN]->[1|0][TS]',
                       'description': 'Reads vacuum switch state.',
                       'example': 'APP_GET_VACUUM_EN',
                       'example_return': '[APP_GET_VACUUM_EN]->[1][12523]'},
 'APP_SET_CHECK_VACUUM': {'name': 'APP_SET_CHECK_VACUUM',
                          'cmd': 'APP_SET_CHECK_VACUUM',
                          'section': 'APP CONTROL',
                          'parameters': 'int/bool; >0 = enable, <=0 = disable',
                          'returns': '[APP_SET_CHECK_VACUUM][arg]->[OK][TS]',
                          'description': 'Enables/disables vacuum safety check. Blocked while process active or app not RUNNING.',
                          'example': 'APP_SET_CHECK_VACUUM 1',
                          'returns_nok': '[APP_SET_CHECK_VACUUM]->[NOK][reason][TS] or [APP_SET_CHECK_VACUUM][arg]->[NOK][reason][TS]',
                          'example_return': '[APP_SET_CHECK_VACUUM][1]->[OK][12523]'},
 'APP_GET_CHECK_VACUUM': {'name': 'APP_GET_CHECK_VACUUM',
                          'cmd': 'APP_GET_CHECK_VACUUM',
                          'section': 'APP CONTROL',
                          'parameters': '~',
                          'returns': '[APP_GET_CHECK_VACUUM]->[1|0][TS]',
                          'description': 'Returns current vacuum-check enable flag.',
                          'example': 'APP_GET_CHECK_VACUUM',
                          'example_return': '[APP_GET_CHECK_VACUUM]->[0][12523]'},
 'APP_DO_LASER_PWR_TEST': {'name': 'APP_DO_LASER_PWR_TEST',
                           'cmd': 'APP_DO_LASER_PWR_TEST',
                           'section': 'APP CONTROL',
                           'parameters': '~',
                           'returns': '[APP_DO_LASER_PWR_TEST]->[OK][TS]',
                           'description': 'Starts calibration / laser power test. Requires app RUNNING, no active process, acceptable '
                                          'vacuum if check enabled, and Peltier enabled.',
                           'example': 'APP_DO_LASER_PWR_TEST',
                           'returns_nok': '[APP_DO_LASER_PWR_TEST]->[NOK][reason][TS]',
                           'example_return': '[APP_DO_LASER_PWR_TEST]->[OK][12523]'},
 'APP_GET_LASER_TEST_RESULT': {'name': 'APP_GET_LASER_TEST_RESULT',
                               'cmd': 'APP_GET_LASER_TEST_RESULT',
                               'section': 'APP CONTROL',
                               'parameters': '~',
                               'returns': '[APP_GET_LASER_TEST_RESULT]->[OK][TS]',
                               'description': 'Returns OK only when calibration result flag is true.',
                               'example': 'APP_GET_LASER_TEST_RESULT',
                               'returns_nok': '[APP_GET_LASER_TEST_RESULT]->[NOK][Laser power test failed or not completed][TS]',
                               'example_return': '[APP_GET_LASER_TEST_RESULT]->[OK][12523]'},
 'APP_GET_LASER_TEST_DATA': {'name': 'APP_GET_LASER_TEST_DATA',
                             'cmd': 'APP_GET_LASER_TEST_DATA',
                             'section': 'APP CONTROL',
                             'parameters': '~',
                             'returns': "Header: [APP_GET_LASER_TEST_DATA]->[Count,N][TS]; then N plain lines 'idx,T1,T2'; then "
                                        '[APP_GET_LASER_TEST_DATA]->[END][TS]',
                             'description': 'Returns captured calibration samples. Blocked while any process is active.',
                             'example': 'APP_GET_LASER_TEST_DATA',
                             'returns_nok': '[APP_GET_LASER_TEST_DATA]->[NOK][reason][TS]',
                             'example_return': '[APP_GET_LASER_TEST_DATA]->[Count,100][12523]',
                             'notes': 'Data lines are NOT wrapped in [APP_GET_LASER_TEST_DATA]->[...] format.'},
 'APP_GET_FW_VERSION': {'name': 'APP_GET_FW_VERSION',
                        'cmd': 'APP_GET_FW_VERSION',
                        'section': 'APP CONTROL',
                        'parameters': '~',
                        'returns': '[APP_GET_FW_VERSION]->[FW_VERSION][SW_GIT_HASH][TS]',
                        'description': 'Returns firmware version and software git hash from parameters.',
                        'example': 'APP_GET_FW_VERSION',
                        'example_return': '[APP_GET_FW_VERSION]->[V15.1][abc1234][12523]'},
 'APP_GET_HW_VERSION': {'name': 'APP_GET_HW_VERSION',
                        'cmd': 'APP_GET_HW_VERSION',
                        'section': 'APP CONTROL',
                        'parameters': '~',
                        'returns': '[APP_GET_HW_VERSION]->[HW_VERSION][HW_GIT_HASH][TS]',
                        'description': 'Returns hardware version and hardware git hash from parameters.',
                        'example': 'APP_GET_HW_VERSION',
                        'example_return': '[APP_GET_HW_VERSION]->[V2.2][def5678][12523]'},
 'APP_GET_STATE': {'name': 'APP_GET_STATE',
                   'cmd': 'APP_GET_STATE',
                   'section': 'APP CONTROL',
                   'parameters': '~',
                   'returns': '[APP_GET_STATE]->[APP_STATE_*][TS]',
                   'description': 'Returns current application state string.',
                   'example': 'APP_GET_STATE',
                   'example_return': '[APP_GET_STATE]->[APP_STATE_RUNNING][12523]'},
 'APP_GET_LAST_ERROR': {'name': 'APP_GET_LAST_ERROR',
                        'cmd': 'APP_GET_LAST_ERROR',
                        'section': 'APP CONTROL',
                        'parameters': '~',
                        'returns': '[APP_GET_LAST_ERROR]->[Error string][APP_ERROR_CODE][TS]',
                        'description': 'Returns application last error string and code.',
                        'example': 'APP_GET_LAST_ERROR',
                        'example_return': '[APP_GET_LAST_ERROR]->[No error][APP_ERROR_NONE][12523]'},
 'APP_CLEAR_ERROR': {'name': 'APP_CLEAR_ERROR',
                     'cmd': 'APP_CLEAR_ERROR',
                     'section': 'APP CONTROL',
                     'parameters': '~',
                     'returns': '[APP_CLEAR_ERROR]->[OK][TS]',
                     'description': 'Attempts to clear application error state. Only has effect if current app state is APP_STATE_ERROR; '
                                    'then app moves to STABILIZING.',
                     'example': 'APP_CLEAR_ERROR',
                     'example_return': '[APP_CLEAR_ERROR]->[OK][12523]'},
 'APP_SET_GENERAL_PARAMS': {'name': 'APP_SET_GENERAL_PARAMS',
                            'cmd': 'APP_SET_GENERAL_PARAMS',
                            'section': 'APP CONTROL',
                            'parameters': 'VacMax_mbar,RhMin_dP,RhMax_dP,TBoardMin_dC,TBoardMax_dC,THeatsinkMin_dC,THeatsinkMax_dC',
                            'returns': '[APP_SET_GENERAL_PARAMS][args]->[OK][TS]',
                            'description': 'Sets general safety/operation limits. Blocked while process active or app not RUNNING.',
                            'example': 'APP_SET_GENERAL_PARAMS 700,0,500,100,600,100,600',
                            'returns_nok': '[APP_SET_GENERAL_PARAMS][args]->[NOK][reason][TS]',
                            'example_return': '[APP_SET_GENERAL_PARAMS][700,0,500,100,600,100,600]->[OK][12523]'},
 'APP_SET_PELTIER_PARAMS': {'name': 'APP_SET_PELTIER_PARAMS',
                            'cmd': 'APP_SET_PELTIER_PARAMS',
                            'section': 'APP CONTROL',
                            'parameters': 'LaserTempMin_dC,LaserTempMax_dC,LaserTempNominal_dC,Kp,Ki,Kd,Div,iMax',
                            'returns': '[APP_SET_PELTIER_PARAMS][args]->[OK][TS]',
                            'description': 'Sets Peltier operating range and PID values. Blocked while process active or app not RUNNING.',
                            'example': 'APP_SET_PELTIER_PARAMS 200,300,250,10000,10,0,8,10000',
                            'returns_nok': '[APP_SET_PELTIER_PARAMS][args]->[NOK][reason][TS]',
                            'example_return': '[APP_SET_PELTIER_PARAMS][200,300,250,10000,10,0,8,10000]->[OK][12523]'},
 'APP_SET_LASER_PARAMS': {'name': 'APP_SET_LASER_PARAMS',
                          'cmd': 'APP_SET_LASER_PARAMS',
                          'section': 'APP CONTROL',
                          'parameters': 'MaxFireDuration_ms,RedDotPowerPercent',
                          'returns': '[APP_SET_LASER_PARAMS][args]->[OK][TS]',
                          'description': 'Sets max fire duration and red-dot power. Blocked while process active or app not RUNNING.',
                          'example': 'APP_SET_LASER_PARAMS 100,25',
                          'returns_nok': '[APP_SET_LASER_PARAMS][args]->[NOK][reason][TS]',
                          'example_return': '[APP_SET_LASER_PARAMS][100,25]->[OK][12523]'},
 'APP_SET_CALIB_PARAMS': {'name': 'APP_SET_CALIB_PARAMS',
                          'cmd': 'APP_SET_CALIB_PARAMS',
                          'section': 'APP CONTROL',
                          'parameters': 'TolerancePercent,CalibPulseDuration_ms',
                          'returns': '[APP_SET_CALIB_PARAMS][args]->[OK][TS]',
                          'description': 'Sets calibration tolerances and pulse duration. Blocked while process active or app not RUNNING.',
                          'example': 'APP_SET_CALIB_PARAMS 10,100',
                          'returns_nok': '[APP_SET_CALIB_PARAMS][args]->[NOK][reason][TS]',
                          'example_return': '[APP_SET_CALIB_PARAMS][10,100]->[OK][12523]'},
 'APP_GET_GENERAL_PARAMS': {'name': 'APP_GET_GENERAL_PARAMS',
                            'cmd': 'APP_GET_GENERAL_PARAMS',
                            'section': 'APP CONTROL',
                            'parameters': '~',
                            'returns': '[APP_GET_GENERAL_PARAMS]->[VacMax_mbar:...,RhMin_dP:...,RhMax_dP:...,TBoardMin_dC:...,TBoardMax_dC:...,THeatsinkMin_dC:...,THeatsinkMax_dC:...][TS]',
                            'description': 'Returns current general parameters.',
                            'example': 'APP_GET_GENERAL_PARAMS',
                            'example_return': '[APP_GET_GENERAL_PARAMS]->[VacMax_mbar:700,RhMin_dP:0,RhMax_dP:500,TBoardMin_dC:100,TBoardMax_dC:600,THeatsinkMin_dC:100,THeatsinkMax_dC:600][12523]'},
 'APP_GET_PELTIER_PARAMS': {'name': 'APP_GET_PELTIER_PARAMS',
                            'cmd': 'APP_GET_PELTIER_PARAMS',
                            'section': 'APP CONTROL',
                            'parameters': '~',
                            'returns': '[APP_GET_PELTIER_PARAMS]->[LaserTempMin_dC:...,LaserTempMax_dC:...,LaserTempNominal_dC:...,Kp:...,Ki:...,Kd:...,Div:...,iMax:...][TS]',
                            'description': 'Returns current Peltier parameters.',
                            'example': 'APP_GET_PELTIER_PARAMS',
                            'example_return': '[APP_GET_PELTIER_PARAMS]->[LaserTempMin_dC:200,LaserTempMax_dC:300,LaserTempNominal_dC:250,Kp:10000,Ki:10,Kd:0,Div:8,iMax:10000][12523]'},
 'APP_GET_LASER_PARAMS': {'name': 'APP_GET_LASER_PARAMS',
                          'cmd': 'APP_GET_LASER_PARAMS',
                          'section': 'APP CONTROL',
                          'parameters': '~',
                          'returns': '[APP_GET_LASER_PARAMS]->[MaxFireDuration_ms:...,RedDotPowerPercent:...][TS]',
                          'description': 'Returns current laser parameters.',
                          'example': 'APP_GET_LASER_PARAMS',
                          'example_return': '[APP_GET_LASER_PARAMS]->[MaxFireDuration_ms:100,RedDotPowerPercent:25][12523]'},
 'APP_GET_CALIB_PARAMS': {'name': 'APP_GET_CALIB_PARAMS',
                          'cmd': 'APP_GET_CALIB_PARAMS',
                          'section': 'APP CONTROL',
                          'parameters': '~',
                          'returns': 'Intended format string is [APP_GET_CALIB_PARAMS]->[TolerancePercent,CalibPulseDuration_ms][TS] but '
                                     'current code omits value placeholders.',
                          'description': 'Handler tries to print calibration parameters, but format string bug means values are not '
                                         'inserted as written.',
                          'example': 'APP_GET_CALIB_PARAMS',
                          'example_return': '[APP_GET_CALIB_PARAMS]->[TolerancePercent,CalibPulseDuration_ms][12523]',
                          'notes': 'Bug in implementation: values are passed to Comm_PrintUSB but format string contains no % placeholders '
                                   'for them.'},
 'APP_BOOT': {'name': 'APP_BOOT',
              'cmd': 'APP_BOOT',
              'section': 'APP CONTROL',
              'parameters': '~',
              'returns': '',
              'description': 'Currently not implemented.',
              'example': 'APP_BOOT',
              'returns_nok': '[APP_BOOT]->[NOK][Boot command is not implemented.][TS]',
              'example_return': '[APP_BOOT]->[NOK][Boot command is not implemented.][12523]'},
 'APP_STORE_PARAMS_TO_NVM': {'name': 'APP_STORE_PARAMS_TO_NVM',
                             'cmd': 'APP_STORE_PARAMS_TO_NVM',
                             'section': 'APP CONTROL',
                             'parameters': '~',
                             'returns': '[APP_STORE_PARAMS_TO_NVM]->[OK][TS]',
                             'description': 'Stores current parameters to data EEPROM. Blocked while process active or app not RUNNING.',
                             'example': 'APP_STORE_PARAMS_TO_NVM',
                             'returns_nok': '[APP_STORE_PARAMS_TO_NVM]->[NOK][reason][TS]',
                             'example_return': '[APP_STORE_PARAMS_TO_NVM]->[OK][12523]'},
 'APP_STORE_CALIB_DATA': {'name': 'APP_STORE_CALIB_DATA',
                          'cmd': 'APP_STORE_CALIB_DATA',
                          'section': 'APP CONTROL',
                          'parameters': '~',
                          'returns': '[APP_STORE_CALIB_DATA]->[OK][TS]',
                          'description': 'Copies captured calib data into reference array (average of T1/T2) and marks refDataValid=true. '
                                         'Does not itself write NVM; use APP_STORE_PARAMS_TO_NVM afterwards.',
                          'example': 'APP_STORE_CALIB_DATA',
                          'returns_nok': '[APP_STORE_CALIB_DATA]->[NOK][reason][TS]',
                          'example_return': '[APP_STORE_CALIB_DATA]->[OK][12523]'},
 'APP_SET_PERIODIC_REPORT_EN': {'name': 'APP_SET_PERIODIC_REPORT_EN',
                                'cmd': 'APP_SET_PERIODIC_REPORT_EN',
                                'section': 'APP CONTROL',
                                'parameters': 'int/bool; >0 = enable, <=0 = disable',
                                'returns': '[APP_SET_PERIODIC_REPORT_EN][arg]->[OK][TS]',
                                'description': 'Enables/disables periodic report messages.',
                                'example': 'APP_SET_PERIODIC_REPORT_EN 1',
                                'returns_nok': '[APP_SET_PERIODIC_REPORT_EN][arg]->[NOK][Invalid argument(s)][TS]',
                                'example_return': '[APP_SET_PERIODIC_REPORT_EN][1]->[OK][12523]'},
 'APP_GET_PERIODIC_REPORT_EN': {'name': 'APP_GET_PERIODIC_REPORT_EN',
                                'cmd': 'APP_GET_PERIODIC_REPORT_EN',
                                'section': 'APP CONTROL',
                                'parameters': '~',
                                'returns': '[APP_GET_PERIODIC_REPORT_EN]->[1|0][TS]',
                                'description': 'Returns periodic report enable flag.',
                                'example': 'APP_GET_PERIODIC_REPORT_EN',
                                'example_return': '[APP_GET_PERIODIC_REPORT_EN]->[0][12523]'},
 'APP_SET_PELTIER_DEFAULT_EN': {'name': 'APP_SET_PELTIER_DEFAULT_EN',
                                'cmd': 'APP_SET_PELTIER_DEFAULT_EN',
                                'section': 'APP CONTROL',
                                'parameters': 'int/bool; >0 = enable startup Peltier, <=0 = disable',
                                'returns': '[APP_SET_PELTIER_DEFAULT_EN][arg]->[OK][TS]',
                                'description': 'Sets whether Peltier is automatically enabled after stabilization on startup.',
                                'example': 'APP_SET_PELTIER_DEFAULT_EN 1',
                                'returns_nok': '[APP_SET_PELTIER_DEFAULT_EN][arg]->[NOK][Invalid argument(s)][TS]',
                                'example_return': '[APP_SET_PELTIER_DEFAULT_EN][1]->[OK][12523]'},
 'APP_GET_PELTIER_DEFAULT_EN': {'name': 'APP_GET_PELTIER_DEFAULT_EN',
                                'cmd': 'APP_GET_PELTIER_DEFAULT_EN',
                                'section': 'APP CONTROL',
                                'parameters': '~',
                                'returns': '[APP_GET_PELTIER_DEFAULT_EN]->[1|0][TS]',
                                'description': 'Returns startup default for Peltier enable.',
                                'example': 'APP_GET_PELTIER_DEFAULT_EN',
                                'example_return': '[APP_GET_PELTIER_DEFAULT_EN]->[1][12523]'},
 'APP_RESET_TO_DEFAULTS': {'name': 'APP_RESET_TO_DEFAULTS',
                           'cmd': 'APP_RESET_TO_DEFAULTS',
                           'section': 'APP CONTROL',
                           'parameters': '~',
                           'returns': '[APP_RESET_TO_DEFAULTS]->[OK][TS]',
                           'description': 'Resets in-memory parameters to compiled defaults. Blocked while process active or app not '
                                          'RUNNING.',
                           'example': 'APP_RESET_TO_DEFAULTS',
                           'returns_nok': '[APP_RESET_TO_DEFAULTS]->[NOK][reason][TS]',
                           'example_return': '[APP_RESET_TO_DEFAULTS]->[OK][12523]'},
 'SYSTEM_STABILIZED': {'name': 'SYSTEM_STABILIZED',
                       'cmd': 'SYSTEM_STABILIZED',
                       'section': 'ASYNC MESSAGES',
                       'parameters': '[~]',
                       'returns': '[SYSTEM_STABILIZED]->[TS]',
                       'description': 'After APP_STATE_STABILIZING has lasted APP_STABILIZATION_TIME_MS (1000 ms), just before switching '
                                      'to APP_STATE_RUNNING.',
                       'notes': 'Not in command table, but emitted from App_Task().',
                       'example': '[SYSTEM_STABILIZED]->[12523]'},
 'APP_ERROR_HAPPENED': {'name': 'APP_ERROR_HAPPENED',
                        'cmd': 'APP_ERROR_HAPPENED',
                        'section': 'ASYNC MESSAGES',
                        'parameters': '[~]',
                        'returns': '[APP_ERROR_HAPPENED]->[Error string][APP_ERROR_CODE][TS]',
                        'description': 'When g_appCtx.sendReportOnError is set after App_Fail().',
                        'notes': 'This is the actual code format; old draft had field order reversed.',
                        'example': '[APP_ERROR_HAPPENED]->[Pressure above safety limit][APP_ERROR_UNSAFE_CONDITIONS][12523]'},
 'APP_WATCHDOG_TRIGGERED': {'name': 'APP_WATCHDOG_TRIGGERED',
                            'cmd': 'APP_WATCHDOG_TRIGGERED',
                            'section': 'ASYNC MESSAGES',
                            'parameters': '[~]',
                            'returns': '[APP_WATCHDOG_TRIGGERED]->[TS]',
                            'description': 'When g_appCtx.sendReportOnWatchdogTimeout is set.',
                            'notes': 'Current implementation sends only timestamp. There is also an older duplicate spec in the draft with '
                                     'error text, but not in this code.',
                            'example': '[APP_WATCHDOG_TRIGGERED]->[12523]'},
 'APP_LASER_PWR_TEST_FINISHED': {'name': 'APP_LASER_PWR_TEST_FINISHED',
                                 'cmd': 'APP_LASER_PWR_TEST_FINISHED',
                                 'section': 'ASYNC MESSAGES',
                                 'parameters': '[~]',
                                 'returns': '[APP_LASER_PWR_TEST_FINISHED]->[OK|NOK][TS]',
                                 'description': 'When calibration/power test completes and OnCalibComplete() sets report flag.',
                                 'example': '[APP_LASER_PWR_TEST_FINISHED]->[OK][12523]'},
 'APP_TARGET_SEQ_FINISHED': {'name': 'APP_TARGET_SEQ_FINISHED',
                             'cmd': 'APP_TARGET_SEQ_FINISHED',
                             'section': 'ASYNC MESSAGES',
                             'parameters': '[~]',
                             'returns': '[APP_TARGET_SEQ_FINISHED]->[OK][TARGET_STATE_*][TS]',
                             'description': 'When target sequence completes and OnTargetSequenceCompleted() sets report flag.',
                             'notes': 'Current implementation always prints OK plus final target state string.',
                             'example': '[APP_TARGET_SEQ_FINISHED]->[OK][TARGET_STATE_COMPLETED][12523]'},
 'APP_LOAD_PARAMS_FAILED': {'name': 'APP_LOAD_PARAMS_FAILED',
                            'cmd': 'APP_LOAD_PARAMS_FAILED',
                            'section': 'ASYNC MESSAGES',
                            'parameters': '[~]',
                            'returns': '[APP_LOAD_PARAMS_FAILED]->[Error string][APP_ERROR_CODE][TS]',
                            'description': 'Once after startup if parameters could not be loaded from NVM and defaults are used.',
                            'example': '[APP_LOAD_PARAMS_FAILED]->[Failed to load parameters from NVM, using '
                                       'defaults.][APP_ERROR_NVM][12523]'},
 'ADC:': {'name': 'ADC:',
          'cmd': 'ADC:',
          'section': 'ASYNC MESSAGES',
          'parameters': '[~]',
          'returns': 'ADC: ADCts:<ts>, Iin:<mA>, I660:<mA>, I808:<mA>, I980:<mA>, I1064:<mA>, Pwr:<mV>, Tlaser:<dC>, Vpelt:<mV>, '
                     'Theat:<dC>, Tmos:<dC>, T1:<dC>, T2:<dC>, Gx:<raw>, Gy:<raw>',
          'description': 'Every APP_REPORT_PERIOD_MS (5000 ms) when APP_SET_PERIODIC_REPORT_EN is enabled and app is RUNNING.',
          'notes': 'Plain text line, not wrapped in [CMD]->[...] format.'},
 'I2C:': {'name': 'I2C:',
          'cmd': 'I2C:',
          'section': 'ASYNC MESSAGES',
          'parameters': '[~]',
          'returns': 'I2C:Pts:<ts>, SHTts:<ts>, P:<mBar>, PT:<dC>, Tamb:<dC>, RH:<dP>',
          'description': 'Every APP_REPORT_PERIOD_MS (5000 ms) when periodic reporting is enabled.',
          'notes': 'Plain text line, not wrapped in [CMD]->[...] format.'},
 'APP:': {'name': 'APP:',
          'cmd': 'APP:',
          'section': 'ASYNC MESSAGES',
          'parameters': '[~]',
          'returns': 'APP: '
                     '<APP_STATE>\\nADC:<ADC_STATE>\\nI2C:<I2C_STATE>\\nPELTIER:<PELTIER_STATE>\\nLASER:<LASER_STATE>\\nTARGET:<TARGET_STATE>\\nCALIB:<CALIB_STATE>\\nScheduler<counter>',
          'description': 'Every APP_REPORT_PERIOD_MS (5000 ms) when periodic reporting is enabled.',
          'notes': 'Contains embedded newline characters inside one transmitted string.'}}

COMMAND_GROUPS = {'LASER CONTROL': ['LASER_SET_ARM_EN',
                   'LASER_GET_ARM_EN',
                   'LASER_SET_RED_DOT_EN',
                   'LASER_GET_RED_DOT_EN',
                   'LASER_SET_CHANNEL_PWR',
                   'LASER_GET_CHANNEL_PWR',
                   'LASER_FIRE',
                   'LASER_STOP',
                   'LASER_IS_ACTIVE',
                   'LASER_GET_STATE',
                   'LASER_GET_LAST_ERROR',
                   'LASER_CLEAR_ERROR'],
 'PELTIER CONTROL': ['PELTIER_SET_COOLING_EN',
                     'PELTIER_GET_COOLING_EN',
                     'PELTIER_GET_STATE',
                     'PELTIER_GET_LAST_ERROR',
                     'PELTIER_CLEAR_ERROR'],
 'TARGET CONTROL': ['TARGET_SET_POS',
                    'TARGET_GET_POS',
                    'TARGET_GET_FB_POS',
                    'TARGET_SET_NEW_TARGET',
                    'TARGET_CLEAR_TARGETS',
                    'TARGET_GET_TARGET',
                    'TARGET_GET_ALL_TARGETS',
                    'TARGET_SET_MODE',
                    'TARGET_GET_MODE',
                    'TARGET_START',
                    'TARGET_HALT',
                    'TARGET_STOP',
                    'TARGET_CONTINUE',
                    'TARGET_GET_STATE',
                    'TARGET_GET_LAST_ERROR',
                    'TARGET_CLEAR_ERROR'],
 'SENSOR CONTROL': ['SENSORS_GET_VALUES', 'SENSORS_GET_STATE', 'SENSORS_GET_LAST_ERROR', 'SENSORS_CLEAR_ERROR'],
 'APP CONTROL': ['APP_PING',
                 'APP_GET_COMMANDS',
                 'APP_GET_LIMITS',
                 'APP_RESET',
                 'APP_GET_PROC_TIME',
                 'APP_SET_VACUUM_EN',
                 'APP_GET_VACUUM_EN',
                 'APP_SET_CHECK_VACUUM',
                 'APP_GET_CHECK_VACUUM',
                 'APP_DO_LASER_PWR_TEST',
                 'APP_GET_LASER_TEST_RESULT',
                 'APP_GET_LASER_TEST_DATA',
                 'APP_GET_FW_VERSION',
                 'APP_GET_HW_VERSION',
                 'APP_GET_STATE',
                 'APP_GET_LAST_ERROR',
                 'APP_CLEAR_ERROR',
                 'APP_SET_GENERAL_PARAMS',
                 'APP_SET_PELTIER_PARAMS',
                 'APP_SET_LASER_PARAMS',
                 'APP_SET_CALIB_PARAMS',
                 'APP_GET_GENERAL_PARAMS',
                 'APP_GET_PELTIER_PARAMS',
                 'APP_GET_LASER_PARAMS',
                 'APP_GET_CALIB_PARAMS',
                 'APP_BOOT',
                 'APP_STORE_PARAMS_TO_NVM',
                 'APP_STORE_CALIB_DATA',
                 'APP_SET_PERIODIC_REPORT_EN',
                 'APP_GET_PERIODIC_REPORT_EN',
                 'APP_SET_PELTIER_DEFAULT_EN',
                 'APP_GET_PELTIER_DEFAULT_EN',
                 'APP_RESET_TO_DEFAULTS'],
 'ASYNC MESSAGES': ['SYSTEM_STABILIZED',
                    'APP_ERROR_HAPPENED',
                    'APP_WATCHDOG_TRIGGERED',
                    'APP_LASER_PWR_TEST_FINISHED',
                    'APP_TARGET_SEQ_FINISHED',
                    'APP_LOAD_PARAMS_FAILED',
                    'ADC:',
                    'I2C:',
                    'APP:']}

ERROR_CODES = {'ERR_NO_VACUUM': 'No vacuum present. Eg. by calling LASER_SET_ARM_EN 1',
 'ERR_LASER_TEMP': 'Laser temp out of normal range.',
 'ERR_SEQ_IN_PROG': 'Sequence already running.',
 'ERR_LASER_ACTIVE': 'Laser currently active. (LASER_FIRE was just sent)',
 'ERR_GALVO_FAULT': 'Galvo fault pin IT occoured.',
 'ERR_OUT_OF_RANGE': 'Parameter specified out of range.',
 'ERR_SENS_FAILURE': 'Sensor failure occoured.',
 'ERR_NOT_ARMED': 'Laser is not armed.',
 'ERR_INVALID_CMD': 'Invalid command or missing parameters.',
 'ERR_INVALID_OPERATION': 'Invalid operation in current state.',
 'ERR_ENV_COND': 'Environmental conditions not met. Tboard and RHboard not in specified range.'}

SENSOR_FIELDS = [{'index': 0, 'label': 'INPUT_CURR [mA]', 'raw_key': 'inputCurrent_mA', 'dict_key': 'inputCurrent_mA'},
 {'index': 1, 'label': 'LASER660_CURR [mA]', 'raw_key': 'laser660Curr_mA', 'dict_key': 'laser660Curr_mA'},
 {'index': 2, 'label': 'LASER808_CURR [mA]', 'raw_key': 'laser808Curr_mA', 'dict_key': 'laser808Curr_mA'},
 {'index': 3, 'label': 'LASER980_CURR [mA]', 'raw_key': 'laser980Curr_mA', 'dict_key': 'laser980Curr_mA'},
 {'index': 4, 'label': 'LASER1064_CURR [mA]', 'raw_key': 'laser1064Curr_mA', 'dict_key': 'laser1064Curr_mA'},
 {'index': 5, 'label': 'LASER_POWER [mV]', 'raw_key': 'laserPower_mV', 'dict_key': 'laserPower_mV'},
 {'index': 6, 'label': 'LASER_TEMP [C]', 'raw_key': 'laserTemp_C', 'dict_key': 'laserTemp_C'},
 {'index': 7, 'label': 'PELTIER_VOLTAGE [mV]', 'raw_key': 'peltierVoltage_mV', 'dict_key': 'peltierVoltage_mV'},
 {'index': 8, 'label': 'HEATSINK_TEMP [C]', 'raw_key': 'heatsinkTemp_C', 'dict_key': 'heatsinkTemp_C'},
 {'index': 9, 'label': 'MOSFET_TEMP [C]', 'raw_key': 'mosfetTemp_C', 'dict_key': 'mosfetTemp_C'},
 {'index': 10, 'label': 'TARGET1_TEMP [C]', 'raw_key': 'target1Temp_C', 'dict_key': 'target1Temp_C'},
 {'index': 11, 'label': 'TARGET2_TEMP [C]', 'raw_key': 'target2Temp_C', 'dict_key': 'target2Temp_C'},
 {'index': 12, 'label': 'GALVO_POS_X [raw]', 'raw_key': 'galvoPosX_raw', 'dict_key': 'galvoPosX_raw'},
 {'index': 13, 'label': 'GALVO_POS_Y [raw]', 'raw_key': 'galvoPosY_raw', 'dict_key': 'galvoPosY_raw'},
 {'index': 14, 'label': 'LASER660_OFFSET [mA]', 'raw_key': 'laser660Curr_mA', 'dict_key': 'laser660_offset_ma'},
 {'index': 15, 'label': 'LASER808_OFFSET [mA]', 'raw_key': 'laser808Curr_mA', 'dict_key': 'laser808_offset_ma'},
 {'index': 16, 'label': 'LASER980_OFFSET [mA]', 'raw_key': 'laser980Curr_mA', 'dict_key': 'laser980_offset_ma'},
 {'index': 17, 'label': 'LASER1064_OFFSET [mA]', 'raw_key': 'laser1064Curr_mA', 'dict_key': 'laser1064_offset_ma'},
 {'index': 18, 'label': 'UPDATE_TIMESTAMP [ms]', 'raw_key': 'updateTimestamp_ms', 'dict_key': 'updateTimestamp_ms'}]

ASYNC_MESSAGES = {
    name: meta
    for name, meta in COMMANDS.items()
    if meta["section"] == "ASYNC MESSAGES"
}

RESPONSE_STATUS_TOKENS = {"OK", "NOK", "END"}

def build_command(command_name: str, *params: Any) -> str:
    """Build a serial command string."""
    if not params:
        return command_name
    return f"{command_name} " + ",".join(str(p) for p in params)

def get_command_meta(command_name: str) -> dict:
    """Return metadata for a command."""
    return COMMANDS[command_name]

def sensor_values_to_dict(values: list[Any]) -> dict[str, Any]:
    """Map SENSORS_GET_VALUES payload list to a keyed dictionary.

    Note:
        The spreadsheet contains duplicate raw keys for OFFSET fields.
        To avoid overwriting values, this function uses ``dict_key`` from
        SENSOR_FIELDS, which is guaranteed to be unique.
    """
    result: dict[str, Any] = {}
    for field, value in zip(SENSOR_FIELDS, values):
        result[field["dict_key"]] = value
    return result

def response_payload_tokens(response: Any) -> list[str]:
    """Return bracketed payload tokens after the serial response arrow."""
    tokens: list[str] = []
    lines = response if isinstance(response, (list, tuple)) else [response]
    for line in lines:
        text = str(line)
        if "->" not in text:
            continue
        payload = text.split("->", 1)[1]
        tokens.extend(token.strip() for token in re.findall(r"\[([^\]]*)\]", payload))
    return tokens

def response_data_tokens(response: Any) -> list[str]:
    """Return response payload tokens excluding protocol status markers."""
    return [
        token
        for token in response_payload_tokens(response)
        if token.upper() not in RESPONSE_STATUS_TOKENS
    ]

def response_status(line: Any) -> str | None:
    """Return OK/NOK/END when it is the first payload token."""
    tokens = response_payload_tokens(line)
    if not tokens:
        return None
    status = tokens[0].upper()
    return status if status in RESPONSE_STATUS_TOKENS else None

def is_async_message(message: str) -> bool:
    """Check whether a raw message starts with a known async event name."""
    msg = message.strip()
    for name in ASYNC_MESSAGES:
        if msg.startswith(name) or msg.startswith(f"[{name}]"):
            return True
    return False
